<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0-windows7.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>

    <PropertyGroup>
        <ClassIslandPluginSdkVersion>1.4.0.0</ClassIslandPluginSdkVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ClassIsland.PluginSdk\ClassIsland.PluginSdk.csproj">
            <ExcludeAssets>runtime; native</ExcludeAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <None Update="Icon.ico">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Icon.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="manifest.yml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
